<?php
include_once ('grandfather.php');
class Father extends grandfather
{
    public function __construct($age)
    {
        parent::__construct($age);

    }
    public function run()
    {
        return parent::run(); // TODO: Change the autogenerated stub
    }

    public function sing(){
        return "abc";
}
}
